from pydantic import BaseModel, Field
from typing import List, Optional

class ActionStep(BaseModel):
    """A single staged mitigation action item."""
    id: str = Field(description="UUID or short unique ID for this action")
    action: str = Field(description="Action command or instruction to be executed")
    risk_tag: str = Field(description="Safety gate state: auto_approve, approval_required, blocked")
    risk_level: str = Field(description="Risk rating of execution (low, medium, high, critical)")
    rationale: str = Field(description="Technical rationale for this step")
    verification_check: str = Field(description="Command or check to verify the action succeeded")

class ActionPlan(BaseModel):
    """Mitigation action plan generated by A5 Action Planner."""
    mitigation_steps: List[ActionStep] = Field(default_factory=list, description="Ordered list of recommended steps")
    summary: str = Field(description="Summary of the action plan approach")
    safety_disclaimer: Optional[str] = Field(None, description="Guardrail warnings or safety instructions")
