from pydantic import BaseModel, Field
from typing import List

class Hypothesis(BaseModel):
    """Causal explanation or root-cause hypothesis generated by A3 Correlation."""
    title: str = Field(description="Short title of the hypothesis")
    description: str = Field(description="Explanation of the causal chain")
    causal_factor: str = Field(description="Specific root-cause factor identified")
    confidence: float = Field(description="Confidence score for this hypothesis (0.0 to 1.0)")
    evidence_citations: List[str] = Field(default_factory=list, description="IDs of matching KB docs/postmortems/chats")
    severity_implication: str = Field(description="Estimated severity implication of this root cause")

class HypothesisSet(BaseModel):
    """Ranked set of hypotheses with convergence stats."""
    hypotheses: List[Hypothesis] = Field(default_factory=list, description="Ranked list of hypotheses (top first)")
    convergence_score: float = Field(description="Multi-signal convergence score (0.0 to 1.0)")
    reasoning_path: str = Field(description="Step-by-step causal reasoning text from the model")
