from pydantic import BaseModel, Field
from typing import List, Optional
from datetime import datetime

class AgentTraceSchema(BaseModel):
    """Pydantic model representing the execution trace of a single agent."""
    agent_name: str = Field(description="Name of the agent (e.g. A1, A2)")
    status: str = Field(description="Execution status (running, completed, failed, skipped)")
    model_used: Optional[str] = Field(None, description="LLM model identifier used by the agent")
    duration_ms: Optional[int] = Field(None, description="Execution duration in milliseconds")
    tokens_used: Optional[int] = Field(None, description="Number of tokens consumed by this agent step")
    input_summary: Optional[str] = Field(None, description="Short summary of input sent to the agent")
    output_summary: Optional[str] = Field(None, description="Short summary of output generated by the agent")
    error_message: Optional[str] = Field(None, description="Error details if the agent failed")
    started_at: datetime = Field(default_factory=datetime.utcnow, description="Time execution started")

class PipelineResult(BaseModel):
    """Pydantic model representing the consolidated result of the incident pipeline run."""
    incident_id: str = Field(description="UUID of the incident")
    status: str = Field(description="Final pipeline status: completed, failed")
    traces: List[AgentTraceSchema] = Field(default_factory=list, description="List of per-agent execution traces")
    duration_ms: int = Field(0, description="Total duration of pipeline execution")
    total_tokens: int = Field(0, description="Total tokens consumed by all agents in this run")
