import logging
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy.orm import selectinload

from database import get_db
from auth.dependencies import get_current_user
from models.database import User, Incident

logger = logging.getLogger("aios.routes.postmortem")
router = APIRouter()

@router.post("/incident/{incident_id}/export-postmortem")
async def export_postmortem(
    incident_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Generate and return a standardized markdown postmortem report for a resolved incident."""
    stmt = select(Incident).where(Incident.id == incident_id).options(
        selectinload(Incident.traces),
        selectinload(Incident.actions)
    )
    res = await db.execute(stmt)
    incident = res.scalars().first()
    
    if not incident:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Incident with ID {incident_id} not found."
        )

    # Compile the postmortem report in Markdown format
    md = f"""# SRE Retrospective Postmortem Report
## Incident #{incident.id[:8]}: {incident.title}

---

| Metadata | Value |
|---|---|
| **Incident ID** | `{incident.id}` |
| **Service Name** | `{incident.service_name}` |
| **Severity** | `{incident.severity}` |
| **Status** | `{incident.status}` |
| **Created At** | `{incident.created_at.isoformat() if incident.created_at else 'N/A'}` |
| **Resolved At** | `{incident.resolved_at.isoformat() if incident.resolved_at else 'Active Outage'}` |
| **Resolved By** | `{incident.resolved_by or 'N/A'}` |
| **Diagnosis Accuracy** | `{f"{incident.accuracy_score * 100:.1f}%" if incident.accuracy_score is not None else 'N/A'}` |
| **Total Tokens Used** | `{incident.total_tokens or 0}` |
| **Pipeline Duration** | `{f"{incident.pipeline_duration_ms / 1000:.2f}s" if incident.pipeline_duration_ms else 'N/A'}` |

---

### 1. Incident Executive Summary
{incident.executive_view or "No summary available."}

---

### 2. Technical Root Cause Analysis
**Operator Resolution Notes:**
> {incident.actual_root_cause or "Pending resolution notes."}

**Top System Hypothesis:**
{incident.hypotheses.get("hypotheses", [{}])[0].get("description", "No hypotheses loaded.") if isinstance(incident.hypotheses, dict) and incident.hypotheses.get("hypotheses") else "No hypothesis generated."}

---

### 3. Timeline of SRE Actions Taken
"""

    if incident.actions:
        for idx, act in enumerate(incident.actions, 1):
            md += f"{idx}. **Action:** `{act.action}`\n"
            md += f"   - Risk: {act.risk_level.upper()} ({act.risk_tag})\n"
            md += f"   - Status: {act.status.upper()}\n"
            md += f"   - Approved By: {act.approved_by or 'N/A'}\n"
            md += f"   - Verification: {act.verification_check}\n\n"
    else:
        md += "_No actions logged for this incident._\n"

    md += """
---

### 4. Agent Trace Log (Observability Audit Trail)
"""

    if incident.traces:
        for t in incident.traces:
            md += f"- **Agent:** `{t.agent_name}` | Status: `{t.status}` | Duration: `{t.duration_ms}ms` | Model: `{t.model_used}`\n"
            if t.error_message:
                md += f"  - *Error:* {t.error_message}\n"
    else:
        md += "_No agent traces captured._\n"

    md += """
---
*Generated by AIOS — Agentic Incident Operating System*
"""

    return {
        "incident_id": incident_id,
        "filename": f"postmortem_{incident_id[:8]}.md",
        "markdown": md
    }
